import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.scss";
import styles from "./layout.module.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable}`}>
      <body>
        <div className={styles.container}>
          {children}
        </div>
      </body>
    </html>
  );
}
